apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
      - name: streamlit-container
        image: dockeruser2004/finalproject:latest
        ports:
        - containerPort: 8500
        - containerPort: 8501
        - containerPort: 8502