version: '3.8'

services:

  landing-page:
    build: .
    image: dockeruser2004/landing-page:latest
    ports:
      - "8502:8502"
    restart: always

  multimodal-creator:
    build: ./manufacturing-creator
    image: dockeruser2004/multimodal-creator:latest
    ports:
      - "8500:8500"
    env_file:
      - ./manufacturing-creator/.env
    restart: always

  multi-agent:
    build: ./multi-agent-manufacturing
    image: dockeruser2004/multi-agent:latest
    ports:
      - "8501:8501"
    env_file:
      - ./multi-agent-manufacturing/.env
    restart: always